package kodlamaio.hrms.business.concretes.cvInformationManagers;

import kodlamaio.hrms.business.abstracts.cvInformationServices.CandidateExperienceInformationService;
import kodlamaio.hrms.business.abstracts.cvInformationServices.CandidateWebAddressService;

public class CandidateExperienceInformationManager implements CandidateExperienceInformationService{

}
