package kodlamaio.hrms.business.concretes.cvInformationManagers;

import kodlamaio.hrms.business.abstracts.cvInformationServices.CandidateEducationInformationService;
import kodlamaio.hrms.business.abstracts.cvInformationServices.CandidateWebAddressService;

public class CandidateEducationInformationManager implements CandidateEducationInformationService{

}
